build.gradle, src/main/java/com/insidemovie/backend/api/sample/controller/SampleController.java, src/main/java/com/insidemovie/backend/common/advice/ControllerExceptionAdvice.java, src/main/java/com/insidemovie/backend/common/config/swagger/SwaggerConfig.java, src/main/java/com/insidemovie/backend/common/entity/BaseTimeEntity.java, src/main/java/com/insidemovie/backend/common/exception/BadRequestException.java, src/main/java/com/insidemovie/backend/common/exception/BaseException.java, src/main/java/com/insidemovie/backend/common/exception/InternalServerException.java, src/main/java/com/insidemovie/backend/common/exception/NotFoundException.java, src/main/java/com/insidemovie/backend/common/exception/UnAuthorizedException.java, src/main/java/com/insidemovie/backend/common/response/ApiResponse.java, src/main/java/com/insidemovie/backend/common/response/ErrorStatus.java, src/main/java/com/insidemovie/backend/common/response/SuccessStatus.java
- close #1 
프로젝트 공통 코드 추가
Swagger 설정
=> [FEAT] 프로젝트 공통 코드 추가, Swagger 설정

src/main/java/com/insidemovie/backend/api/sample/entity/User.java
=> [FEAT] 엔티티 또연습..

.github/workflows/change-pr-base.yml
=> [FEAT] CI 설정

src/main/java/com/insidemovie/backend/common/config/swagger/SwaggerConfig.java
- close #18 
Swagger Authorize 설정
Swagger 접속 주소 : http://localhost:8080/swagger-ui/index.html
=> [FEAT] Swagger Authorize 설정

src/main/java/com/insidemovie/backend/api/report/controller/ReportController.java, src/main/java/com/insidemovie/backend/api/report/entity/Report.java, src/main/java/com/insidemovie/backend/api/report/repository/ReportRepository.java, src/main/java/com/insidemovie/backend/api/report/service/ReportService.java, src/main/java/com/insidemovie/backend/common/response/ErrorStatus.java, src/main/java/com/insidemovie/backend/common/response/SuccessStatus.java
=> [FEAT] 리뷰 신고 기능 구현

src/main/java/com/insidemovie/backend/api/admin/controller/AdminController.java, src/main/java/com/insidemovie/backend/api/admin/dto/AdminMemberDTO.java, src/main/java/com/insidemovie/backend/api/admin/service/AdminMemberService.java, src/main/java/com/insidemovie/backend/api/jwt/JwtProvider.java, src/main/java/com/insidemovie/backend/api/member/controller/MemberController.java, src/main/java/com/insidemovie/backend/api/member/entity/Member.java, src/main/java/com/insidemovie/backend/api/member/repository/MemberRepository.java, src/main/java/com/insidemovie/backend/api/review/controller/ReviewController.java, src/main/java/com/insidemovie/backend/api/review/repository/ReviewRepository.java, src/main/java/com/insidemovie/backend/common/config/security/SecurityConfig.java, src/main/java/com/insidemovie/backend/common/response/SuccessStatus.java
- close #40 
- 관리자 권한으로 회원 목록을 조회, 검색, 정지 기능
- 회원 탈퇴는 추후 구현 예정
=> [FEAT] 관리자 회원 관리 기능 구현

dummy.ts
=> chore: dummy commit to reopen PR

src/main/java/com/insidemovie/backend/api/jwt/JwtFilter.java, src/main/java/com/insidemovie/backend/api/member/entity/Member.java, src/main/java/com/insidemovie/backend/api/report/entity/Report.java, src/main/java/com/insidemovie/backend/api/review/entity/Review.java, src/main/resources/application.yml
- close #66 
- JwtFilter에 있던 디버깅용 System.out.println 제거
- @Builder.Default를 통해 초기값 설정 경고 해결
=> [FIX] @Builder 필드 초기값 누락 경고 해결

src/main/resources/application.yml
- close #75 
카카오 RedirectURI 수정
=> [FIX] 카카오 RedirectURI 수정

src/main/java/com/insidemovie/backend/api/member/controller/MemberController.java, src/main/java/com/insidemovie/backend/api/member/dto/MemberInfoDto.java, src/main/java/com/insidemovie/backend/api/member/service/MemberService.java
- close #84 
회원 정보 조회 구현
사용자의 프로필을 조회하는 API입니다.
아직 사용자의 감정이 연동되지 않고 기본 프로필만 조회하니 나중에 추가해주시면 감사하겠습니다.
=> [FEAT] 회원 정보 조회 구현

src/main/java/com/insidemovie/backend/api/movie/controller/MovieController.java, src/main/java/com/insidemovie/backend/api/movie/service/MovieService.java, src/main/java/com/insidemovie/backend/common/config/security/SecurityConfig.java
=> [FIX] 코드 오타 및 오류 수정

src/main/java/com/insidemovie/backend/api/member/controller/MemberController.java, src/main/java/com/insidemovie/backend/api/member/service/MemberService.java
- close #100 
이메일 회원가입, 카카오 회원가입 시 감정 분석 결과를 저장하기 위해 memberId 반환값 추가
100번째 이슈 당첨!
=> [FEAT] 이메일 회원가입, 카카오 회원가입 반환값 추가

src/main/java/com/insidemovie/backend/api/movie/controller/MovieController.java, src/main/java/com/insidemovie/backend/api/movie/dto/MovieDetailResDto.java, src/main/java/com/insidemovie/backend/api/movie/repository/MovieLikeRepository.java, src/main/java/com/insidemovie/backend/api/movie/service/MovieDetailService.java, src/main/java/com/insidemovie/backend/api/movie/service/MovieLikeService.java, src/main/java/com/insidemovie/backend/common/config/security/SecurityConfig.java, src/main/java/com/insidemovie/backend/common/response/SuccessStatus.java
- close #94
영화 좋아요 기능 추가
영화 상세보기 시 좋아요 눌렀는지 반환하는 것 추가
지금 장르 쪽 문제 있어서 아직 조회는 안 되는 상태입니다
=> Feat/#94 영화 좋아요 기능 추가

src/main/java/com/insidemovie/backend/api/member/controller/MemberController.java, src/main/java/com/insidemovie/backend/api/member/dto/ProfileEmotionUpdateRequestDto.java, src/main/java/com/insidemovie/backend/api/member/entity/Member.java, src/main/java/com/insidemovie/backend/api/member/service/MemberService.java, src/main/java/com/insidemovie/backend/common/response/SuccessStatus.java
- close #98 
- 마이페이지에서 프로필 이미지 변경 기능 구현
- Member 엔티티에 EmotionType enum타입의 필드 추가
=> [FEAT] 프로필 이미지 변경 기능 구현

src/main/java/com/insidemovie/backend/api/movie/controller/MovieController.java
=> [FIX] 세미콜론 추가

src/main/java/com/insidemovie/backend/api/movie/controller/MovieController.java, src/main/java/com/insidemovie/backend/api/review/controller/ReviewController.java, src/main/java/com/insidemovie/backend/api/review/dto/ReviewCreateDTO.java, src/main/java/com/insidemovie/backend/api/review/dto/ReviewUpdateDTO.java, src/main/java/com/insidemovie/backend/api/review/service/ReviewService.java, src/main/java/com/insidemovie/backend/common/config/security/SecurityConfig.java
- close #107 
- 기존 /api/v1/review 엔드포인트를 /api/v1/movies/{movieId}/reviews 등 RESTful 구조로 리팩토링
- 리뷰 등록, 조회, 수정, 삭제, 좋아요 API 엔드포인트 변경
=> [REFAC] 리뷰 API 구조 변경

src/main/java/com/insidemovie/backend/api/constant/GenreType.java, src/main/java/com/insidemovie/backend/api/movie/controller/MovieController.java, src/main/java/com/insidemovie/backend/api/movie/dto/MovieSearchReqDto.java, src/main/java/com/insidemovie/backend/api/movie/dto/MovieSearchResDto.java, src/main/java/com/insidemovie/backend/api/movie/dto/PageResDto.java, src/main/java/com/insidemovie/backend/api/movie/dto/tmdb/SearchMovieResponseDTO.java, src/main/java/com/insidemovie/backend/api/movie/entity/Movie.java, src/main/java/com/insidemovie/backend/api/movie/entity/MovieGenre.java, src/main/java/com/insidemovie/backend/api/movie/repository/GenreRepository.java, src/main/java/com/insidemovie/backend/api/movie/repository/MovieGenreRepository.java, src/main/java/com/insidemovie/backend/api/movie/repository/MovieRepository.java, src/main/java/com/insidemovie/backend/api/movie/scheduler/MovieUpdateScheduler.java, src/main/java/com/insidemovie/backend/api/movie/service/MovieDetailService.java, src/main/java/com/insidemovie/backend/api/movie/service/MovieService.java, src/main/java/com/insidemovie/backend/common/response/SuccessStatus.java, src/main/resources/application.yml
- close #74 
- TMDB API로부터 받아오는 영화 장르 저장 로직 개선  
- GenreType enum 기반 매핑 도입  
- 영화 제목 검색 기능 추가  
- 제목 키워드로 검색 시 `MovieSearchResDto` 리스트 반환  
- 페이징(PageResDto) 지원
- MovieServie 에서 applyDetailToMovie 메서드 수정!! 확인!!🌟🌟
=> [FEAT]영화 타이틀로 검색 기능

src/main/java/com/insidemovie/backend/api/movie/service/MovieDetailService.java, src/main/java/com/insidemovie/backend/api/movie/service/MovieService.java
=> [FIX] 오류 수정

src/main/java/com/insidemovie/backend/api/member/controller/MemberController.java, src/main/java/com/insidemovie/backend/api/member/dto/NicknameCheckResponseDTO.java, src/main/java/com/insidemovie/backend/api/member/service/MemberService.java, src/main/java/com/insidemovie/backend/common/response/SuccessStatus.java
- close #114 
- 닉네임 중복 여부 확인
- 중복되는 닉네임 있으면 true, 없으면 false
=> [FEAT] 닉네임 중복 확인 기능 추가

src/main/java/com/insidemovie/backend/api/movie/controller/MovieController.java, src/main/java/com/insidemovie/backend/api/movie/repository/MovieRepository.java, src/main/java/com/insidemovie/backend/api/movie/service/MovieService.java, src/main/java/com/insidemovie/backend/common/response/SuccessStatus.java
- close #81
- DB에서 TMDB `popularity` 열 데이터를 이용하여 정렬한 인기순 데이터 반환 기능 추가
=> [FEAT] 인기 영화 조회 기능 추가

src/main/java/com/insidemovie/backend/common/config/security/SecurityConfig.java
- close #121 
닉네임 수정 SecurityConfig 엔드포인트 추가
=> [FIX] 닉네임 수정 SecurityConfig 엔드포인트 추가

src/main/java/com/insidemovie/backend/api/movie/service/MovieService.java
- close #125 
TMDB ID를 Movie ID로 변경하여 응답 데이터 구조 수정
=> [REFAC] TMDB ID를 Movie ID로 변경하여 응답 데이터 구조 수정

src/main/java/com/insidemovie/backend/api/member/controller/MemberController.java, src/main/java/com/insidemovie/backend/api/member/dto/MemberInfoDto.java, src/main/java/com/insidemovie/backend/api/member/service/MemberService.java, src/main/java/com/insidemovie/backend/api/movie/repository/MovieLikeRepository.java, src/main/java/com/insidemovie/backend/common/response/SuccessStatus.java
- close #127 
사용자 정보 조회 시 사용자 감정 상태, 좋아요 개수 등 반환 값 추가
=> [FEAT] 사용자 정보 조회 시 사용자 감정 상태, 좋아요 개수 등 반환 값 추가

src/main/java/com/insidemovie/backend/api/constant/GenreType.java, src/main/java/com/insidemovie/backend/api/movie/controller/MovieController.java, src/main/java/com/insidemovie/backend/api/movie/dto/PageResDto.java, src/main/java/com/insidemovie/backend/api/movie/dto/RecommendedMovieReqDto.java, src/main/java/com/insidemovie/backend/api/movie/dto/RecommendedMovieResDto.java, src/main/java/com/insidemovie/backend/api/movie/entity/MovieGenre.java, src/main/java/com/insidemovie/backend/api/movie/repository/MovieGenreRepository.java, src/main/java/com/insidemovie/backend/api/movie/repository/MovieLikeRepository.java, src/main/java/com/insidemovie/backend/api/movie/repository/MovieRepository.java, src/main/java/com/insidemovie/backend/api/movie/service/MovieService.java, src/main/java/com/insidemovie/backend/common/response/ErrorStatus.java, src/main/java/com/insidemovie/backend/common/response/SuccessStatus.java
- close #120 
- 장르를 선택하면 장르에 맞는 영화를 최신 순으로 추천
- - 장르를 선택하면 장르에 맞는 영화를 평점 순으로 추천
=> [FEAT]영화 장르별 추천 

src/main/java/com/insidemovie/backend/api/constant/EmotionType.java, src/main/java/com/insidemovie/backend/api/member/controller/MemberController.java, src/main/java/com/insidemovie/backend/api/movie/dto/MyMovieResponseDTO.java, src/main/java/com/insidemovie/backend/api/movie/dto/PageResDto.java, src/main/java/com/insidemovie/backend/api/movie/repository/MovieEmotionSummaryRepository.java, src/main/java/com/insidemovie/backend/api/movie/repository/MovieLikeRepository.java, src/main/java/com/insidemovie/backend/api/movie/service/MovieLikeService.java, src/main/java/com/insidemovie/backend/common/response/ErrorStatus.java
- close #136
좋아요한 영화 목록 응답에 포스터, 평점, 감정, 영화제목 정보 추가
=> [FEAT] 마이페이지에서 내가 좋아요 한 영화 목록 응답 데이터 추가

src/main/java/com/insidemovie/backend/api/admin/controller/AdminController.java, src/main/java/com/insidemovie/backend/api/member/controller/MemberController.java, src/main/java/com/insidemovie/backend/api/review/controller/ReviewController.java, src/main/java/com/insidemovie/backend/common/response/PageResult.java
- close #138 
- 공통 페이지 DTO PageResult<T> 만듬
- 표준 필드: page, size, totalElements, totalPages, last, content 포함
- 제 것만 수정했습니다
=> [REFAC] 페이지네이션 응답 구조 PageResult로 변경

src/main/java/com/insidemovie/backend/api/movie/service/MovieService.java, src/main/java/com/insidemovie/backend/common/response/SuccessStatus.java
- close #145 
- 리뷰가 없는 영화에서 감정 평균 조회 시 대표 감정이 JOY로 나와서 NEUTRAL로 수정
=> [FIX] 영화 감정 상태 리뷰가 하나도 없을 때 대표 감정이 JOY로 나오는 거 NEUTRAL로 수정

src/main/java/com/insidemovie/backend/api/member/controller/MemberController.java, src/main/java/com/insidemovie/backend/api/review/service/ReviewService.java
- close #148 
마이페이지에서 내가 작성한 리뷰 목록 응답 ReviewResponseDTO 으로 변경하여 데이터 추가
=> [FEAT] 마이페이지에서 내가 작성한 리뷰 목록 응답 데이터 추가

src/main/java/com/insidemovie/backend/api/member/controller/MemberController.java, src/main/java/com/insidemovie/backend/api/movie/dto/MovieSearchResDto.java, src/main/java/com/insidemovie/backend/api/movie/service/MovieLikeService.java, src/main/java/com/insidemovie/backend/api/movie/service/MovieService.java, src/main/java/com/insidemovie/backend/common/response/SuccessStatus.java
- close #152 
- 내가 작성한 리뷰는 관람한 영화 목록에서 확인 가능하도록 추가
=> [FEAT] 내가 본 영화 리스트 조회 기능

src/main/java/com/insidemovie/backend/api/member/controller/MemberController.java, src/main/java/com/insidemovie/backend/api/member/dto/PasswordUpdateRequestDTO.java, src/main/java/com/insidemovie/backend/api/member/service/MemberService.java, src/main/java/com/insidemovie/backend/common/response/ErrorStatus.java
- close #155 
비밀번호 변경 수정
내가 작성한 리뷰 조회 반환 값 오류 수정
API 동작하는지 확인은 하고 PR 합시다!
=> [FIX] 비밀번호 변경 수정

src/main/java/com/insidemovie/backend/api/member/controller/MemberController.java
- close #154 
- 잘못된 머지로 인해 응답 데이터 이상 발생
- 정상적인 응답 구조로 복구
=> [FIX] 내가 작성한 리뷰 조회 응답 데이터 수정

src/main/java/com/insidemovie/backend/api/member/dto/PasswordUpdateRequestDTO.java, src/main/java/com/insidemovie/backend/api/member/service/MemberService.java
- close #159 
비밀번호 수정 시 예외 처리를 추가했습니다
- 비밀번호랑 비밀번호 재확인 값이 다를 경우 예외처리
- 현재 비밀번호가 일치하지 않는 경우 예외처리
- 현재 비밀번호와 변경할 비밀번호가 같은 경우 예외처리
=> [FIX] 비밀번호 수정 예외 처리

src/main/java/com/insidemovie/backend/api/movie/controller/MovieController.java, src/main/java/com/insidemovie/backend/api/movie/dto/MovieSearchResDto.java, src/main/java/com/insidemovie/backend/api/movie/service/MovieService.java
- close #158 
- 영화 타이틀 검색 정보 응답에 mainEmotion 속성 추가
- 영화 장르 별 추천 정보 응답에 mainEmotion 속성 추가
- 영화 타이틀 검색 정보 응답에 mainEmotion 속성 추가
=> [FEAT] 영화 정보 응답에 mainEmotion 속성 추가

src/main/java/com/insidemovie/backend/api/member/controller/MemberController.java, src/main/java/com/insidemovie/backend/api/member/dto/MemberInfoDto.java, src/main/java/com/insidemovie/backend/api/member/service/MemberService.java, src/main/java/com/insidemovie/backend/api/review/service/ReviewService.java
- close #162 
사용자 정보 조회 리뷰 개수(본 영화 개수) 추가
=> [FEAT] 사용자 정보 조회 리뷰 개수(본 영화 개수) 추가

build.gradle, src/main/java/com/insidemovie/backend/api/constant/EmotionType.java, src/main/java/com/insidemovie/backend/api/member/dto/emotion/EmotionAvgDTO.java, src/main/java/com/insidemovie/backend/api/member/dto/emotion/MemberEmotionSummaryRequestDTO.java, src/main/java/com/insidemovie/backend/api/member/dto/emotion/MemberEmotionSummaryResponseDTO.java, src/main/java/com/insidemovie/backend/api/member/entity/MemberEmotionSummary.java, src/main/java/com/insidemovie/backend/api/member/service/MemberService.java, src/main/java/com/insidemovie/backend/api/movie/dto/emotion/MovieEmotionSummaryResponseDTO.java, src/main/java/com/insidemovie/backend/api/movie/entity/MovieEmotionSummary.java, src/main/java/com/insidemovie/backend/api/movie/service/MovieService.java, src/main/java/com/insidemovie/backend/api/recommend/dto/EmotionRequestDTO.java, src/main/java/com/insidemovie/backend/api/recommend/service/EmotionRecommendationService.java, src/main/java/com/insidemovie/backend/api/review/dto/EmotionDTO.java, src/main/java/com/insidemovie/backend/api/review/entity/Emotion.java, src/main/java/com/insidemovie/backend/api/review/repository/EmotionRepository.java, src/main/java/com/insidemovie/backend/api/review/service/ReviewService.java, src/main/resources/application-local.yml, src/main/resources/application-prod.yml, src/main/resources/application.yml, src/main/resources/db/migration/V2__rename_neutral_to_disgust.sql
- close #170 
데이터 마이그레이션 작업 롤백
=> Revert "Merge pull request #150 from AutoeverInsideMovie/refac/#141"

src/main/java/com/insidemovie/backend/api/report/controller/ReportController.java, src/main/java/com/insidemovie/backend/api/report/service/ReportService.java, src/main/java/com/insidemovie/backend/api/review/dto/ReviewResponseDTO.java, src/main/java/com/insidemovie/backend/api/review/service/ReviewService.java
- close #168 
- 리뷰 조회하면 report, conceal null로 나오는거 true/false로 수정
- 신고 접수 시에는 계속 false로 하고 신고 수락하면 true로 변경
=> [FIX] 신고하면 리뷰에 반영 안 되는 오류 수정

src/main/java/com/insidemovie/backend/api/movie/service/MovieDetailService.java
- close #169 
- 장르 없는 영화 조회 시 예외 발생 -> 장르 없어도 상세 보기 응답 되도록
=> [FIX] 장르 없는 영화 조회 시 예외 발생

src/main/java/com/insidemovie/backend/api/review/controller/ReviewController.java, src/main/java/com/insidemovie/backend/api/review/service/ReviewService.java, src/main/java/com/insidemovie/backend/common/config/security/SecurityConfig.java
- close #177 
맞춤 영화 SecurityConfig 엔드포인트 추가
=> [FIX] 맞춤 영화 SecurityConfig 엔드포인트 추가

src/main/java/com/insidemovie/backend/api/movie/dto/MovieDetailResDto.java, src/main/java/com/insidemovie/backend/api/movie/service/MovieDetailService.java
- close #175 
- 영화 상세보기 응답 데이터 추가
=> [FEAT] 영화 상세보기 응답 데이터 추가

src/main/java/com/insidemovie/backend/api/review/service/ReviewService.java
- close #187 
- ReviewService 중복 코드 제거 및 메서드 간소화
- 불필요한 주석 및 System.out 출력문 제거로 가독성 개선
=> [FIX] ReviewService 중복 코드 제거 및 메서드 간소화

src/main/java/com/insidemovie/backend/api/constant/ReviewSort.java, src/main/java/com/insidemovie/backend/api/review/constant/ReviewSortType.java, src/main/java/com/insidemovie/backend/api/review/controller/ReviewController.java, src/main/java/com/insidemovie/backend/api/review/service/ReviewService.java
- close #191 
- 영화 리뷰 목록에 정렬 기능 추가 (최신순, 오래된순, 좋아요순)
- 마이페이지 내가 작성한 리뷰 목록은 최신순으로 정렬
=> [FEAT] 리뷰 목록에 정렬 기능 추가

src/main/java/com/insidemovie/backend/api/member/entity/Member.java, src/main/java/com/insidemovie/backend/api/member/entity/MemberEmotionSummary.java, src/main/java/com/insidemovie/backend/api/member/service/MemberService.java, src/main/java/com/insidemovie/backend/api/report/controller/ReportController.java, src/main/java/com/insidemovie/backend/api/review/controller/ReviewController.java, src/main/java/com/insidemovie/backend/common/exception/ForbiddenException.java, src/main/java/com/insidemovie/backend/common/exception/UnAuthorizedException.java, src/main/java/com/insidemovie/backend/common/response/ErrorStatus.java, src/main/java/com/insidemovie/backend/common/response/SuccessStatus.java
- close #190 
- 정지된 사용자 리뷰 작성, 신고 기능 사용할 수 없도록 서버 측 제한 추가 (403 Forbidden)
=> [FEAT] 정지된 사용자 리뷰 작성 및 신고 기능 제한

src/main/java/com/insidemovie/backend/common/config/security/SecurityConfig.java
- close #201 
SecurityConfig 예외 추가
=> [FIX] SecurityConfig 예외 추가

src/main/java/com/insidemovie/backend/api/review/service/ReviewService.java
- close #207 
- 영화 리뷰 목록 내 리뷰 보이도록 수정
-  감정분석 할 때 값이 0이면 리뷰 작성 시 생기는 오류 수정
=> [FIX] 영화 리뷰 목록에 내 리뷰가 보이도록 수정

src/main/java/com/insidemovie/backend/api/review/dto/ReviewResponseDTO.java, src/main/java/com/insidemovie/backend/api/review/service/ReviewService.java
- close #214 
리뷰 DTO 영화 관람일 반환값 추가
=> [FIX] 리뷰 DTO 영화 관람일 반환값 추가

src/main/java/com/insidemovie/backend/api/member/dto/emotion/EmotionAvgDTO.java, src/main/java/com/insidemovie/backend/api/member/entity/MemberEmotionSummary.java, src/main/java/com/insidemovie/backend/api/member/service/MemberService.java, src/main/java/com/insidemovie/backend/api/movie/service/MovieService.java, src/main/java/com/insidemovie/backend/api/review/service/ReviewService.java
- close #213 
- 리뷰 작성 시 MemberEmotionSummary에 업데이트
- 리뷰 작성 시 MovieEmotionSummary에 업데이트
- 리뷰 하나도 없을 때 대표 감정 NONE으로 설정
=> [FIX] 리뷰 작성 시 영화/사용자 감정 정보 업데이트 누락 수정

src/main/java/com/insidemovie/backend/api/match/entity/Match.java, src/main/java/com/insidemovie/backend/api/member/entity/Member.java, src/main/java/com/insidemovie/backend/api/movie/entity/Movie.java, src/main/java/com/insidemovie/backend/api/movie/entity/MovieEmotionSummary.java, src/main/java/com/insidemovie/backend/api/review/entity/Review.java
=> [FIX] fetch 변경

src/main/java/com/insidemovie/backend/api/member/controller/MemberController.java, src/main/java/com/insidemovie/backend/api/member/dto/emotion/MemberEmotionSummaryRequestDTO.java, src/main/java/com/insidemovie/backend/api/member/dto/emotion/MemberEmotionSummaryResponseDTO.java, src/main/java/com/insidemovie/backend/api/member/service/MemberService.java
- close #227 사용자 감정 상태 업데이트 기능 수정
- 입력으로 사용자의 액세스 토큰 요청
- 평균값을 반환하던 메서드를 데이터 수정 메서드로 로직 변경\
=> [REFAC] 사용자의 감성 상태 업데이트 기능 수정

src/main/java/com/insidemovie/backend/api/movie/dto/boxoffice/DailyBoxOfficeResponseDTO.java, src/main/java/com/insidemovie/backend/api/movie/dto/boxoffice/WeeklyBoxOfficeResponseDTO.java, src/main/java/com/insidemovie/backend/api/movie/repository/MovieEmotionSummaryRepository.java, src/main/java/com/insidemovie/backend/api/movie/service/BoxOfficeService.java
=> [FIX] 박스오피스 응답 구조 개선

src/main/java/com/insidemovie/backend/api/member/dto/MemberLoginResponseDto.java, src/main/java/com/insidemovie/backend/api/member/service/MemberService.java
- close #239 
이메일 로그인 시 ROLE 반환 추가
=> [FEAT] 이메일 로그인 시 ROLE 반환 추가

src/main/java/com/insidemovie/backend/api/member/repository/MemberEmotionSummaryRepository.java, src/main/java/com/insidemovie/backend/api/member/repository/MemberLikeRepository.java, src/main/java/com/insidemovie/backend/api/member/service/MemberEmotionSummaryService.java, src/main/java/com/insidemovie/backend/api/movie/repository/MovieLikeRepository.java, src/main/java/com/insidemovie/backend/api/movie/service/MovieEmotionSummaryService.java, src/main/java/com/insidemovie/backend/api/review/repository/ReviewRepository.java, src/main/java/com/insidemovie/backend/api/review/service/ReviewService.java
- close #236 
사용자가 좋아요한 영화 감정 상태 변경 시, 자동으로 사용자의 감정 상태 변경 기능 추가
=> [FEAT] 사용자가 좋아요한 영화 감정 상태 변경 시, 자동으로 사용자의 감정 상태 변경 기능 추가

src/main/java/com/insidemovie/backend/api/member/repository/MemberEmotionSummaryRepository.java, src/main/java/com/insidemovie/backend/api/review/dto/ReviewResponseDTO.java, src/main/java/com/insidemovie/backend/api/review/service/ReviewService.java
- close #242 
- movies/search/title 
- movies/recommend/popular 
- movies/recommend/latest 
- 응답에 memberEmotion 대표감정 추가
=> [FEAT] 리뷰 응답에 사용자 대표 감정(memberEmotion) 추가

src/main/java/com/insidemovie/backend/api/review/entity/Review.java, src/main/java/com/insidemovie/backend/api/review/service/ReviewService.java
- close #248
Review 엔티티 modify 삭제
=> [FIX] Review 엔티티 modify 삭제

build.gradle, src/main/java/com/insidemovie/backend/api/Email/Service/EmailService.java, src/main/java/com/insidemovie/backend/api/Email/controller/EmailController.java, src/main/java/com/insidemovie/backend/common/config/security/SecurityConfig.java, src/main/java/com/insidemovie/backend/common/response/SuccessStatus.java, src/main/resources/application.yml
- close #253 
- 사용자가 회원 가입 시 이메일 입력 후 이메일 인증하도록
=> [FEAT] 이메일 인증 기능
